#!/usr/bin/env python3

import time
import colors as c
import random

sides = []

sides.append('''
 -------
|       |
| Gein  |
|      1|
 -------
''')

sides.append('''
 -------
|       |
| Zein  |
|      2|
 -------
''')

sides.append('''
 -------
|       |
|  Sed  |
|      3|
 -------
''')

sides.append('''
 -------
|       |
|  Hir  |
|      4|
 -------
''')

sides.append('''
 -------
|       |
|  Hen  |
|      5|
 -------
''')

sides.append('''
 -------
|       |
|  Sok  |
|      6|
 -------
''')

 
for side in sides:
    print(c.clear + c.random_color() + random.choice(sides) + c.reset)
    time.sleep(0.6)
