#!/usr/bin/env python3

import time
import colors as c

seconds = 0
hundredths = 0
minutes = 0
hours = 0
days = 0

try:
    while True:
        print(c.clear + c.cyan + '[Control-C to quit]: ' + c.reset)
        print(seconds)
        print(hundredths)
        print(hours)
        print(days)
        print(minutes)
        time.sleep(0.01)
        hundredth += 1
        if hundredths == 100:
            seconds += 1
            hundredths = 0
        if seconds == 60:
            minutes += 1
            seconds = 0
        if minutes == 60:
            hours += 1
            minutes = 0
        if hours == 24:
            days += 1
            hours = 0



except:
    print("\b\bByeLooser" + c.reset)
    exit()








