#!/usr/bin/env python3

import time
import colors as c

print(c.clear)




snake = '''
____ _  _ ____ _  _ ____   /  /
[__  |\ | |__| |_/  |___  /  / 
___] | \| |  | | \_ |___ .  . 

'''

while True:
    for verse in range(5):

        for badger in range(12):
            print("Badgers!")
            time.sleep(0.4)

        for mushrooms in range(2):
            print('Mushroom!')
            time.sleep(0.8)

        time.sleep(0.38)
        print(c.clear)

    print(c.clear)
    print(snake)
    time.sleep(6)

